sub asy {return system("asy '$_[0]'");}
add_cus_dep("asy","eps",0,"asy");
add_cus_dep("asy","pdf",0,"asy");
add_cus_dep("asy","tex",0,"asy");
$pdf_previewer = 'start zathura';
$pdf_mode=2;
$latex = 'latex -interaction=nonstopmode -shell-escape';
